### ISSUE TITLE
failed to work with the latest firebase-admin version

### ISSUE THREAD

**Issue by ruby-ts** [VirgilSecurity/e3kit-firebase-func#34]
Looks like the new version of firebase-admin added some variables into the global namespace, which `e3kit.getVirgilJwt()` couldn't cope with.

```
-    "firebase-admin": "^9.4.2",
+    "firebase-admin": "^9.2.0",
```

**Comment by ruby-ts** [comment]
The error message:
```
Unhandled error RangeError: Failed to construct 'TextDecoder': The encoding label provided ('utf-16le') is invalid.
    at new k (/workspace/node_modules/fast-text-encoding/text.min.js:1:134)
    at new <anonymous> (/workspace/node_modules/@virgilsecurity/core-foundation/node.cjs.js:1:1935)
```

 `google-gax` is a new dependency of firebase-admin. And  `google-gax` requires "fast-text-encoding": "^1.0.3" ,  which polyfill for `TextEncoder()`. Virgil detects if TexeDector() function exists. If yes, use that. I guess before this upgrade, Virgil won't find TextEncoder and won't try to use it.
